#!/usr/bin/expect -f
set timeout 60
set password "Sipanda123#"
set host "157.10.252.74"
set user "sipanda"

spawn ssh $user@$host
expect "password:"
send "$password\r"
expect "$ "

send "sudo tail -n 20 /var/log/nginx/error.log\r"
expect {
    "password for sipanda:" {
        send "$password\r"
        exp_continue
    }
    "$ "
}

send "sudo tail -n 20 /var/log/nginx/access.log\r"
expect "$ "

send "exit\r"
expect eof
